spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/pertemuan11_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pertemuan_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:abcde}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect

server.port=8080

spring.thymeleaf.cache=false
